services:
  nginx:
      image: nginx:latest
      restart: unless-stopped
      tty: true
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/my-app.conf
      ports:
        - "80:80"
      depends_on:
        - pengi-chatbot
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  pengi-chatbot:
    image: khanhduong2003/pengi-chatbot
    container_name: pengi-chatbot
    volumes:
      - pengi-data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 9999:9999
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  pengi-data: {}
